### ISSUE TITLE
Wrong where clause lead to wrong generated SQL

### ISSUE THREAD

**Issue by anayrat** [powa-team/powa-web#102]
Hello,

In several part we have such where clause:
```python
.where(c.calls is not None)
```

Which was translated in SQL with `WHERE true`.

It seems the fix is replace it by:
```python
.where(c.calls != '0')
```

Which is translated in
```
WHERE anon_1.calls != '0'
```

**Comment by anayrat** [comment]
More precisely, it is not always the case.

I greped each location where we use `.where(c.calls `:

  * https://github.com/powa-team/powa-web/blob/master/powa/server.py#L245
  * https://github.com/powa-team/powa-web/blob/master/powa/database.py#L155

And a variant `c.calls != None` in :
  * https://github.com/powa-team/powa-web/blob/master/powa/query.py#L240

I don't know why, but in server.py and database.py `c.calls is not None` is translated to `true`.
But in query.py we have `c.calls != None` which is translated to `anon_1.calls IS NOT NULL`

I am pretty sure we must change to `c.calls != '0'` in server.py and database.py. For query.py I must spend more time on it.

**Comment by rjuju** [comment]
Good catch!

**Comment by anayrat** [comment]
After investigation `c.calls != None` in query.py must be changed to `c.calls != '0'`.
