### ISSUE TITLE
Can powa-web be installed on separate server than the repository database in a remote setup?

### ISSUE THREAD

**Issue by hrawulwa** [powa-team/powa-web#115]
Hello,
I have a remote setup where, Powa-collector, powa-web and repository database all run on a single DB server.
As per our company policy, the DB and web components should be separated, and cannot run on a single DB server.
Is it possible to configure and install powa-web on a separate app server?
This is the current powa-web conf file.
servers={
  'main': {
    'host': 'localhost',
    'port': '5432',
    'database': 'powa',
    'query': {'client_encoding': 'utf8'}
  }
}

If yes, what are the additional steps needed to make it work?
I assume we will be needing the entry of powa-web server IP address in the Repository database pg_hba.conf file?
Please advise.

Thanks
Hari

**Comment by rjuju** [comment]
Hello,
Yes, that's shouldn't be a problem.  I'm assuming that you have some remote servers too?

Your assumption is correct. If you move powa-web to a different servers, the only modifications required are
* update host (or any other connection information) in the powa-web.conf file
* configure the pg_hba.conf on the postgres repository server to make sure that the connection can be opened from this new server, and do a reload.  
* optionally: update the configuration on the remote servers (if any) to make sure powa-web can connect too, if you want to use features that come with remote server connection (index and hypothetical index suggestion mostly)

If you encounter any issue, please provide the powa-web and postgres logs so I can try to help on that!

**Comment by hrawulwa** [comment]
Yes, correct. I have the remote DB servers, which has extensions.
Yes, since I need hypothetical index suggestion as well, I believe, apart from repository DB server, we also need to update pg_hba.conf file on the Remote DB servers to allow connection from the new powa-web server.
Please confirm.

Thanks
Hari

**Comment by rjuju** [comment]
> Yes, since I need hypothetical index suggestion as well, I believe, apart from repository DB server, we also need to update pg_hba.conf file on the Remote DB servers to allow connection from the new powa-web server.
Please confirm.

Correct!
