### ISSUE TITLE
Version 4.1.0 alter extension powa update ERROR:  column "last_present_ts" of relation "powa_statements" already exists

### ISSUE THREAD

**Issue by banlex73** [powa-team/powa-web#121]
Somehow I already had that column in my table.
Fixed:
` alter table powa_statements drop column last_present_ts;
  alter extension powa update;` 

I suspect a bug in powa--4.0.1--4.1.0.sql
should use
`ALTER TABLE public.powa_statements ADD if not exists last_present_ts timestamptz NULL DEFAULT now();
`

**Comment by rjuju** [comment]
The last_present_ts column didn't exist in version 4.0.1, so the upgrade script as-is should work.  Maybe you added this column manually and modified the purge function manually when working on https://github.com/powa-team/powa-archivist/pull/32?

I don't think that the upgrade script should try to detect direct modification of the tables.

**Comment by banlex73** [comment]
Thank you Julien
Yes, Most likely I added that column manually when working on
powa-team/powa-archivist#32
<https://github.com/powa-team/powa-archivist/pull/32>
adding IF NOT EXISTS just a suggestion, it's up to you.

thank you
Andriy

нд, 13 груд. 2020 о 18:27 Julien Rouhaud <notifications@github.com> пише:
