### ISSUE TITLE
Version 4.1.0 requires pg_stat_kcache update too but there's a bug in pg_stat_kcache

### ISSUE THREAD

**Issue by banlex73** [powa-team/powa-web#122]
Notice that all targets (monitored clusters) must have their powa extension upgraded otherwise getting 
Error while inserting data:
   invalid input syntax for type boolean: "10"
   CONTEXT:  COPY powa_kcache_src_tmp, line 1, column top: "10"
   ,Error while inserting data:
Tried to upgrade powa (successfully) but pg_stat_kcache has a bug https://github.com/powa-team/pg_stat_kcache/issues/29
To make powa 4.1.0 work I had to disable  pg_stat_kcache extension for all targets.
`select powa_deactivate_extension()`

**Comment by rjuju** [comment]
Hello,

In order to keep the code simple, you need to have the powa-archivist extension updated on the repository server and all remote servers, but not the other extensions.  The latest update of powa-archivist should take care of detecting if you have pg_stat_kcache 2.2.x or not.  Can you confirm that you updated powa-archivist on all servers.

**Comment by banlex73** [comment]
Hello
on remote server I have powa 4.1.1 and I deactivated pg_stat_kcache for
this target.
NO ISSUE. Thank you for clarification, *(powa-archivist extension updated
on the repository server and all remote servers)*
postgres=# select * from pg_available_extensions where name in
('powa','pg_stat_kcache');
      name      | default_version | installed_version |              comment
----------------+-----------------+-------------------+-----------------------------------
 powa           | 4.1.1           | 4.1.1             | PostgreSQL Workload
Analyser-core
 pg_stat_kcache | 2.2.0           | 2.1.3             | Kernel statistics
gathering
(2 rows)



нд, 13 груд. 2020 о 18:22 Julien Rouhaud <notifications@github.com> пише:

**Comment by rjuju** [comment]
Great, thanks for the confirmation!
