### ISSUE TITLE
POWA configuration page displays Collector status for this instance: stopped

### ISSUE THREAD

**Issue by HerbertKoelman** [powa-team/powa-web#126]
Hello,

This is my first setup of POWA and I failed to understand why the server's config page is displaying `Collector status for this instance: stopped`.

I have installed what I thought was missing : `powa-collector.py`. But I have taylored the configutation file and when I run the command, it's returning 
```
$ powa-collector.py
2021-01-21 16:40:31,574 - INFO  : Starting powa-collector...
2021-01-21 16:40:31,577 - ERROR : Error connecting:
fe_sendauth: no password supplied
```
I have setup the database and added the extension in it. The database I want to monitor is run on the same postgresql instance.

I'm running 
- RedHat 7
- Postgres 12
- powa-collector.noarch               1.1.0-1.rhel7            @pgdg-common
- powa_12.x86_64                      4.1.2-1.rhel7            @pgdg12
- powa_12-web.x86_64                  4.1.2-1.rhel7            @pgdg12

[powa-conf.zip](https://github.com/powa-team/powa-web/files/5850473/powa-conf.zip)

Any suggestion ?

**Comment by banlex73** [comment]
Hello
in *powa-collector.conf *
you are missing a password
{
    "repository": {
        "dsn": "postgresql://powa*:<MYSUPERPWD>*@localhost:5432/powa"
    },
    "debug": false
}


чт, 21 січ. 2021 о 08:00 Herbert Koelman <notifications@github.com> пише:
