### ISSUE TITLE
powa_servers.version column

### ISSUE THREAD

**Issue by banlex73** [powa-team/powa-web#129]
Hello 
wondering if this column supposed to be updated on target version change or I can/should manually update it whenever I update a monitoring target.
Asking, because in my table this column is null for all records.
Thank you in advance.

**Comment by rjuju** [comment]
Hello @banlex73 

This is something new in version 4.1, and it should be automatically updated by powa collector if you're using version 1.1.0 or later (see https://github.com/powa-team/powa-collector/commit/d5538315a2394cf34ebf93cba67e36459c969c2b).

There are some new commits in powa-web that uses this information, to avoid trying to connect on the remote servers (which may not be possible, and if it's adds quite a lot of latency).

If you can't update powa-collector, you can update it manually if you want.  Once you get the new version of powa-collector, it'll update it automatically if needed anyway.

**Comment by banlex73** [comment]
Awesome!
thank you. 
Definitely, I will update pows-collector to the latest available.
Appreciate swift reaction.
