### ISSUE TITLE
Is Version 4.1.1 available via yum repository on CentOS 7?

### ISSUE THREAD

**Issue by banlex73** [powa-team/powa-web#130]
My yum shows me
Installed Packages powa_12-web.x86_64 **4.1.2-1.rhel7**
and **No packages marked for update**
and UI shows me **Version 4.1.0**
but I am pretty sure that version 4.1.1 has been already released.
Thank you in advance.

**Comment by rjuju** [comment]
Hello @banlex73 

You're right, powa-web version 4.1.41 was released 5 days ago.  You can always follow releases at https://github.com/powa-team/powa-web/releases (and similarly for other projects).

Usually the apt/rpm packages follows a bit later as it requires some packager attention.  It's however unclear to me why you have powa_12-web version 4.1.2, as this version is only a version for powa-archivist (see https://github.com/powa-team/powa-archivist/releases)/

**Comment by banlex73** [comment]
Thank you for clarifying me.
by the way, I thought that  powa_12-web is a Web UI and* powa_12
is powa-archivist *

вт, 16 лют. 2021 о 10:33 Julien Rouhaud <notifications@github.com> пише:

**Comment by rjuju** [comment]
That's the case:

```
$ yum info powa_12-web
[...]
Installed Packages
Name        : powa_12-web
Arch        : x86_64
Version     : 4.1.2
Release     : 1.rhel7
[...]
Summary     : The user interface of powa

$ yum info powa_12
[...]
Installed Packages
Name        : powa_12
Arch        : x86_64
Version     : 4.1.2
Release     : 1.rhel7
[...]
Summary     : PostgreSQL Workload Analyzer
```

Apparently the rpm package has a single version for both UI and postgres extension, while containing a specific version for powa-web, see https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/master/non-common/powa/master/powa.spec;h=6162c0d91d567c69509846d868b302b9b1fb0bb5;hb=HEAD#l9

It should only be a matter of time before an updated version (I'm assuming a -2 version) is published for the UI.

Let me know if that doesn't happen with a week or so.

**Comment by banlex73** [comment]
Thank you for such a detailed answer!

**Comment by banlex73** [comment]
I am writing to confirm that it is still the issue.
yum list powa_12-web.x86_64 
shows me **4.1.2-1.rhel7**
and powa-collector is **1.1.0-1.rhel7** what is **powa-collector.py version 0.0.3**

**Comment by rjuju** [comment]
Thanks for the reminder!

> and powa-collector is 1.1.0-1.rhel7 what is powa-collector.py version 0.0.3

I just tried on a freshly setup centos8, and I get:
```
# rpm -qa | grep powa-collector
powa-collector-1.1.0-1.rhel8.noarch

# powa-collector.py --version
powa-collector.py version 1.1.0
```

It looks ok to me.

But indeed:
```
# rpm -qa | grep powa_12
powa_12-4.1.2-1.rhel8.x86_64
powa_12-web-4.1.2-1.rhel8.x86_64

# grep version /usr/pgsql-12/share/extension/powa.control
default_version = '4.1.2'

# grep VERSION /usr/lib/python3.6/site-packages/powa/__init__.py 
__VERSION__ = '4.1.0'
```

@devrimgunduz is there any reason for using the powa-archivist version for both powa-archivist and powa-web rpm packages?  For the record we maintain a compatibility between those two using the first 2 digits, so any powa-archivist 4.1.x is compatible with any powa-web version 4.1.x, and we they both have different release lifecycle (and typically the UI is released more often).

For now powa-web is in version 4.1.1, is it possible to have an updated rpm, like powa_12-web-1.1.2-2?

I would be happy to send a patch for that.  Does it need more work than bumping powawebversion and adding a changelog in https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/master/non-common/powa/master/powa.spec;h=6162c0d91d567c69509846d868b302b9b1fb0bb5;hb=HEAD#l9 ?

For next release, should I try to send patch for the RPMs or is there any way I can help?

**Comment by banlex73** [comment]
found what was wrong with pows-collector:
`/usr/bin/python2 /bin/powa-collector.py --version
powa-collector.py version 0.0.3
[root@postgres-prd-uscentral1-powa-0 ~]# /usr/bin/python3 /bin/powa-collector.py --version
powa-collector.py version 1.1.0`
version output depends on python version

**Comment by rjuju** [comment]
Ah I see.  Indeed different python version will have different path to find the actual code.

But the powa-collector.py scripts has a proper shebang that (currently) specify python3, and it should be executable, so simply executing it like
```
powa-collector.py --option...
```

will launch the correct version.

**Comment by banlex73** [comment]
Thanks a lot for clarification!
