### ISSUE TITLE
Impossible to suggest indexes: please enable support for pg_qualstats

### ISSUE THREAD

**Issue by progial-sas** [powa-team/powa-web#138]
Hi,
First, thanks for your job, powa is very useful!

I have a similar problem to #123 but all of our package are up to date.
We migrate psql instance from 11 to 13 last week and upgrade all dependancies.

I check all point in #123 . 
I do a powa snapshot in debug mode and rowcount = 70

Now, we have:
![Capture](https://user-images.githubusercontent.com/86596993/123609609-18a50680-d800-11eb-801f-ff44e3f84ca6.PNG)

I test powa in 4.1.1 version and another test with qualstat in 2.0.2 but problem still there.

We have migrated 2 instances and both of them have this behavior. Have you any idea ?
Regards ,

**Comment by rjuju** [comment]
Hi,
Thanks a lot!

Indeed, it looks like another problem in extension detection.  Are you using local mode or remote mode?  For the record version 4.1.2 fixed a related problem in local mode (https://github.com/powa-team/powa-web/commit/60efdb3d222c4b880e45195fa69b542da46a0cb6).

**Comment by progial-sas** [comment]
We use local mode .
It's a little weird , our package is tag 4.1.2 but 60efdb3 fix is not present.
Neither this https://github.com/powa-team/powa-web/issues/123#issuecomment-748977067

We change python code , compile project, kill powa collector , but problem seem still there.

**Comment by rjuju** [comment]
> It's a little weird , our package is tag 4.1.2 but 60efdb3 fix is not present.

Are you using the rpm pgdg packages?  If yes, I already reported it (see https://github.com/powa-team/powa-web/issues/130#issuecomment-791241091) but didn't have any answer for now.  I'm assuming that the packages have been built assuming that both powa-archivist and powa-web would always have the same version, but it's not the case and we have a requirement on `major.minor` only.

> We change python code , compile project, kill powa collector , but problem seem still there.

Did you mean powa-web?

**Comment by progial-sas** [comment]
>Are you using the rpm pgdg packages? 

Yes it is absolutely true...
`grep VERSION /usr/lib/python3.6/site-packages/powa/__init__.py
__VERSION__ = '4.1.0'`

>Did you mean powa-web?

No, we change code in /usr/lib/python3.6/site-packages/powa/framework.py.
Maybe there is an easy way to do it.

**Comment by rjuju** [comment]
> Yes it is absolutely true...
grep VERSION /usr/lib/python3.6/site-packages/powa/__init__.py __VERSION__ = '4.1.0'

Ah then you're 2 patch releases late :(

@devrimgunduz do you plan to publish a new package for  powa-web 4.1.2, and is there anything I can do to help the packaging?  I think it would be good to have different powa-archivist and powa-web packages versions.

> No, we change code in /usr/lib/python3.6/site-packages/powa/framework.py.

I was wondering about killing powa-collector.  If you're using the local mode you shouldn't be using it, as powa-collector will explicitly ignore the local server.  Also, did you restart powa-web after the changes?  I think it should be reloaded automatically by it doesn't hurt to make sure.

> Maybe there is an easy way to do it.

Unfortunately no, and I think that manually modifying files handles by packages can have some bad effect on RHEL and similar.

What you could do is download current version (either a zip/tgz archive or clone the repository), stop the powa-web service and manually start this freshly downloaded version instead.  If that fixes your problem at least we'll know that you're only missing a more recent package.

**Comment by devrimgunduz** [comment]
Done. 4.1.2-3 is in the RPM repos.

**Comment by rjuju** [comment]
Thanks a lot Devrim!

**Comment by progial-sas** [comment]
Awesomes guys ! 
Thanks both of you , it works very well!

**Comment by rjuju** [comment]
Great news!
