### ISSUE TITLE
many index suggestions, only one tested with hypopg

### ISSUE THREAD

**Issue by yhuelf** [powa-team/powa-web#147]
![Screenshot from 2021-09-14 16-43-43](https://user-images.githubusercontent.com/1352144/133283501-0cc88395-18bc-430e-bea0-c1fe9f3ca8e0.png)

**Comment by rjuju** [comment]
I'm assuming that the other queries couldn't be denormalized, and as such couldn't be tested.  It's hard to be certain without access to the data.  Maybe there's some additional info in the javascript console?

**Comment by yhuelf** [comment]
It is probably the case, indeed: with a larger time window comes more index suggestions. Sorry for the noise!
