### ISSUE TITLE
hypopg extension not availabe in Web

### ISSUE THREAD

**Issue by MikhailSaynukov** [powa-team/powa-web#148]
Hi!

trying to install Powa in Remote architecture, remote serves successfully initialised and I can see statistics but in Configuration for remote servers hypopg extension showing as is unavailable. HypoPG was installed on remote servers and seen in Postgres:

postgres=# \dx
                     List of installed extensions
   Name   | Version |   Schema   |             Description             
----------+---------+------------+-------------------------------------
 hypopg   | 1.2.0   | public     | Hypothetical indexes for PostgreSQL
 pgcrypto | 1.3     | public     | cryptographic functions
 plpgsql  | 1.0     | pg_catalog | PL/pgSQL procedural language
(3 rows)

But in web interface the following data can be seen:

![image](https://user-images.githubusercontent.com/45457049/138692587-abaf9332-9888-4712-9065-98151552228f.png)

Please advise how to check proper installation and how to fix this in Configuration tab?

**Comment by rjuju** [comment]
Hi @MikhailSaynukov.  I'm really sorry for the time it took to take care of it, but I just released version 1.2.0 of powa-collector.  It's available on github and published on pypi too, and I also pushed an updated container image.

**Comment by banlex73** [comment]
great news regarding powa-collector! Wondering if it is available via yum ?

пт, 11 лют. 2022 р. о 21:19 Julien Rouhaud ***@***.***> пише:

**Comment by rjuju** [comment]
It looks like it's packaged in the PGDG repository sources, but I don't find it in the list of RPMs on the website.  It's been regularly maintained so I'm assuming it's available, and yum search will show you in which package it's.
