### ISSUE TITLE
Does Powa use Apache log4j internally?

### ISSUE THREAD

**Issue by hrawulwa** [powa-team/powa-web#150]
Does Powa use Apache log4j internally anywhere within the tool?
Our security team has asked to identify any existence of Ingrianlog4j-api-2.10.0.jar and Ingrianlog4j-core-2.10.0.jar and upgrade the latest version of log4j (2.16), in order to fix vulnerabilities.

Thanks
Hari

**Comment by rjuju** [comment]
Hi,

log4j is a java library, and powa relies on either C / plpgsql extensions or python code.  Nothing in powa uses log4j.

**Comment by hrawulwa** [comment]
Great, thanks for the confirmation.
