### ISSUE TITLE
No example values with pg_qualstats

### ISSUE THREAD

**Issue by tbe** [powa-team/powa-web#153]
On partitioned tables, the Predicates tab does not generate execution plans, as there are no example values. The Predicates contain at least one entry for each table:
![image](https://user-images.githubusercontent.com/102155/156165784-ffd5d78b-40bc-4338-935a-2b1cf936ba96.png)

Only some of them contains actually a list of "Most executed values".

**Comment by tbe** [comment]
After some research, we found out this issue affects non-partitioned tables also. In fact, most of our databases have the same issue.

The reason for that seems to be inside the collection / aggregate logic, and not in Powa-Web. I will open an issue at the Archivist project instead

**Comment by rjuju** [comment]
Oh ok.  That's interesting.  Thanks a lot, waiting for the new issue!
