### ISSUE TITLE
Missing extensions in configuration tab --PoWA Web

### ISSUE THREAD

**Issue by Ravi160492** [powa-team/powa-web#157]
Hi,

In PoWA remote server, I have hypopg and pg_track_settings installed.
![Screenshot 2022-06-24 at 2 15 57 PM](https://user-images.githubusercontent.com/4301942/175500425-82fab6b8-af9a-421e-bc00-64a3644c3a6e.png)

But when I check in powa web -> configuration -> server name. I see these 2 extensions are not installed, available and enabled, as seen in the screenshot below. Also these are not collecting any data.

![Screenshot 2022-06-24 at 2 17 36 PM](https://user-images.githubusercontent.com/4301942/175500455-ac2b6e9d-e237-41d3-95bc-755eb06bfba0.png)

In the POWA repository, I have powa and pg_stat_statements extensions.

Did I miss any configuration for these 2 extensions?

**Comment by rjuju** [comment]
First of all, it's unfortunately not very well documented but pg_track_settings is an "external" extension that provides its own infrastructure for powa compatibility.  Therefore it needs to be installed on the repository server too.

This may not fix the problem, but in any case that will be required if you want to gather this extension data for your remote server(s).

Then, I'm wondering if you did specify pg_track_setting extension when registering the remote server?  Can you show the content of powa_extensions and powa_functions for the given server?  Something like:

```
SELECT * FROM powa_extensions WHERE srvid = $mysrvid;
SELECT * FROM powa_functions WHERE srvid = $mysrvid;
```

Finally, for hypopg this is expected.  It's not a stat extension and is needed if you want powa to automatically check if suggested indexes would be used.  Therefore even if hypopg is installed in the remote server on the powa database, it's likely that you will need it in your application database instead.

**Comment by Ravi160492** [comment]
Hi 

So yes, pg_track_settings was not activated in the powa repository database.

![Screenshot 2022-06-24 at 3 39 43 PM](https://user-images.githubusercontent.com/4301942/175514142-f0600dc3-d55c-4751-b58f-dad92451e915.png)

So I have activated it using powa_activate_extension as seen above.

I have to install and create both (pg_track_settings and hypopg) extensions in a remote server inside the database - powa or actually database (prod/test) or in both databases.

**Comment by Ravi160492** [comment]
After activating the extension for srvid 3 using powa_activate_extension  and restarting the collector process I am getting the below errors.  Do I have to install pg_track_settings in powa repository as well.

![Screenshot 2022-06-24 at 3 46 08 PM](https://user-images.githubusercontent.com/4301942/175515345-8994e9b3-da23-4575-8ea9-b7d77b3e7e76.png)

**Comment by rjuju** [comment]
Yes, I mentioned that first in my previous answer:

> First of all, it's unfortunately not very well documented but pg_track_settings is an "external" extension that provides its own infrastructure for powa compatibility. Therefore it needs to be installed on the repository server too.
>
> This may not fix the problem, but in any case that will be required if you want to gather this extension data for your remote server(s).

Everything should work fine automatically as soon as the extension is installed on the repository server, without needed to restart anything.

> Hypopg I have installed in remote server powa DB and application DB both. so that looks good?

Yes it should.  If there's any problem you will have an explicit message saying that hypopg isn't available on the needed database.

**Comment by Ravi160492** [comment]
Thank you for confirmation.
I have pg_track_settings installed and created in powa db(repository db) and remote server (powa and app db) but still receiving errors in powa-web.

> After activating the extension for srvid 3 using powa_activate_extension and restarting the collector process I am getting the below errors. 
> 
> ![Screenshot 2022-06-24 at 3 46 08 PM](https://user-images.githubusercontent.com/4301942/175515345-8994e9b3-da23-4575-8ea9-b7d77b3e7e76.png)

**Comment by rjuju** [comment]
Did the errors eventually cleaned up at the next snapshot, or could you otherwise fix the problem?

**Comment by Ravi160492** [comment]
After couple next snapshots ... error was still there. So I have removed for now. I'll try again.

**Comment by rjuju** [comment]
That's strange.  Was the extension installed in both remote and repository server in the powa-dedicated database?

Anyway, feel free to reopen the issue or create another one if you come back to it.
