### ISSUE TITLE
improved server dropdown

### ISSUE THREAD

**Issue by simonuwe** [powa-team/powa-web#158]
When many server are configured the dropdown list will be quite long and the default behaviour of <select> allows th jump to the first entry starting with th pressed charact only.
A more siutable  selection is using an input filed with and datalist.
Here you can enter a word and all entries containing this word are shown in the drop down.

This could be modified by changing in login.html the 

```
{% apply field(name="server
...
{% end %}
```

to

```
	  {% apply field(name="server", label=_("Server"), list="serverlist") %}{% end %}
	  <datalist id="serverlist">
            {% for opt in sorted(servers().keys()) %}
            <option value="{{opt}}"></option>
            {% end %}
	   </datalist>
```

**Comment by simonuwe** [comment]
```
	  {% apply field(name="server", label=_("Server"), list="serverlist") %}{% end %}
	  <datalist id="serverlist">
            {% for opt in sorted(servers().keys()) %}
            <option value="{{opt}}"></option>
            {% end %}
	   </datalist>
```

**Comment by rjuju** [comment]
Hi,

I agree and I wanted to change the current dropdown list for quite some time, but never found the time to look into it. Using a datalist looks exactly like what I wanted, so thanks a lot!  Do you want to send a PR or should I take care of it?

**Comment by simonuwe** [comment]
#159

**Comment by rjuju** [comment]
It looks good, so merged.  Thanks a lot!
