### ISSUE TITLE
Unable to launch powa web

### ISSUE THREAD

**Issue by abgarg2022** [powa-team/powa-web#161]
powa-web conf has details as below

![image](https://user-images.githubusercontent.com/114390414/194541225-8ca4ae23-2567-4e51-a139-55aaf4917dae.png)

Extension details of powa database(DBName = ioc )
![image](https://user-images.githubusercontent.com/114390414/194541618-b8402045-ec28-4ff0-ab42-1c80cae1e5fd.png)

Running powa wb as below but how to get UI ??
![image](https://user-images.githubusercontent.com/114390414/194541795-85c5d00f-68a4-4ec8-8d53-19729bc0c91c.png)

**Comment by rjuju** [comment]
hi

I'm not sure that I fully understand the problem. have you tried opening
the given URL in your browser? it should understand that 0.0.0.0 is your
local address.

**Comment by abgarg2022** [comment]
> hi I'm not sure that I fully understand the problem. have you tried opening the given URL in your browser? it should understand that 0.0.0.0 is your local address.

Hi,
I got postgresql on ubuntu and installed powa also at same place.
Can you please guide me with pg_hba.conf setup or something else as URL http://0.0.0.0:8888/ is not yielding anything.

**Comment by rjuju** [comment]
>
> I got postgresql on ubuntu and installed powa also at same place.
> Can you please guide me with pg_hba.conf setup or something else as URL
> http://0.0.0.0:8888/ is not yielding anything.
>
do you get an error, an empty page or it's just hitting a timeout?

is this Ubuntu your local machine or a vm or some other distant server?

>

**Comment by abgarg2022** [comment]
> I got postgresql on ubuntu and installed powa also at same place. Can you please guide me with pg_hba.conf setup or something else as URL http://0.0.0.0:8888/ is not yielding anything.
> do you get an error, an empty page or it's just hitting a timeout? is this Ubuntu your local machine or a vm or some other distant server?
> […](#)

Yes.
ubuntu is VM.

![image](https://user-images.githubusercontent.com/114390414/194545574-fa474b48-040b-47c7-b099-5550a10f5ffb.png)

**Comment by abgarg2022** [comment]
Do I need to add my windows Public IP in Security Group of configured VM and then try this URL again?

**Comment by rjuju** [comment]
>
> ubuntu is VM.
>
> ah that explains it
powa-web is acting as a web server, so you need to configure your server if
you want to access it from outside of the vm. one simple way to do that
would be to authorize the 8888 tcp port in the vm firewall if any, and use
instead the ip of that vm in the URL, still with the 8888 port. you should
probably have already done that to accees your postgres server from outside
the vm.

>

**Comment by abgarg2022** [comment]
@rjuju 

To access postgres server, we are using SSH tunnel and private key. How can we access powa UI in such a case?

**Comment by rjuju** [comment]
>
> To access postgres server, we are using SSH tunnel and private key. How
> can we access powa UI in such a case?
>
I'm confused. it means you have to get a shell on the vm to then connect to
postgres? how is your application able to connect then?
but anyway, it means that you made the SSH port (22) available from outside
the vm. you just need to do the exact same thing with the port 8888 and the
UI will be available the same as SSH.

**Comment by abgarg2022** [comment]
Got the UI running now after enabling port 8888, but getting this error now

![image](https://user-images.githubusercontent.com/114390414/194550860-37aac5fc-ee37-43b1-8a9a-a1be01e3ac79.png)

**Comment by rjuju** [comment]
>
> Got the UI running now after enabling port 8888
>
good news!

> , but getting this error now
>

you have a version mismatch between the extension and the UI. how did you
install both powa-archivist and powa-web to have different supported
versions?

>

**Comment by abgarg2022** [comment]
@rjuju 

Followed from https://powa.readthedocs.io/en/latest/quickstart.html#id2

Can we connect over Teams Meeting ? 

https://teams.microsoft.com/l/meetup-join/19%3ameeting_ODk0MzAxYzQtMGIzZS00YTk1LTg4YTEtNjg0ODE3Y2M0MTRj%40thread.v2/0?context=%7b%22Tid%22%3a%225d471751-9675-428d-917b-70f44f9630b0%22%2c%22Oid%22%3a%2243a98f6c-0805-4dd0-92fa-26663c1cf7ab%22%7d

**Comment by rjuju** [comment]
It doesn't say which method you used.  Since you're using ubuntu, the preferred installation method would be from pgdg repository, and looking at the content right now:

- http://apt.postgresql.org/pub/repos/apt/pool/main/p/powa-archivist/ powa-archivist is in version 4.1.4
- http://apt.postgresql.org/pub/repos/apt/pool/main/p/powa-web/ powa web is in version 4.1.3

So I don't know you you installed powa-web, but you made a mistake somewhere.  You need to make sure that you have a version 4.1.x, ideally the latest version which is currently 4.1.3

**Comment by abgarg2022** [comment]
> It doesn't say which method you used. Since you're using ubuntu, the preferred installation method would be from pgdg repository, and looking at the content right now:
> 
> * http://apt.postgresql.org/pub/repos/apt/pool/main/p/powa-archivist/ powa-archivist is in version 4.1.4
> * http://apt.postgresql.org/pub/repos/apt/pool/main/p/powa-web/ powa web is in version 4.1.3
> 
> So I don't know how you installed powa-web, but you made a mistake somewhere. You need to make sure that you have a version 4.1.x, ideally the latest version which is currently 4.1.3

I had used below commands

1. wget https://github.com/powa-team/powa-archivist/archive/REL_4_0_0.tar.gz
2. apt-get install postgresql-12-powa postgresql-12-pg-qualstats postgresql-12-pg-stat-kcache postgresql-12-hypopg

**Comment by rjuju** [comment]
> wget https://github.com/powa-team/powa-archivist/archive/REL_4_0_0.tar.gz
> apt-get install postgresql-12-powa 

So you downloaded powa-archivist 4.0.0 and also installed the latest version of powa-archivist via tha packages?

Given the error you're not using powa-archivist 4.0.0.  And it's still lacking any information about powa-web.

**Comment by abgarg2022** [comment]
> > wget https://github.com/powa-team/powa-archivist/archive/REL_4_0_0.tar.gz
> > apt-get install postgresql-12-powa
> 
> So you downloaded powa-archivist 4.0.0 and also installed the latest version of powa-archivist via tha packages?
> 
> Given the error you're not using powa-archivist 4.0.0. And it's still lacking any information about powa-web.

@rjuju 

Powa web was installed as per https://powa.readthedocs.io/en/latest/quickstart.html#install-powa-web-anywhere

sudo pip install powa-web

**Comment by rjuju** [comment]
But on pypi the current version is 4.1.3: https://pypi.org/project/powa-web/

and your installation says it's 4.0.x.  It looks like you installed multiple version and you're not using the correct one.

**Comment by abgarg2022** [comment]
This seems to be available now

![image](https://user-images.githubusercontent.com/114390414/194800430-97eaa646-685a-42e5-af92-980227c91bd4.png)

**Comment by abgarg2022** [comment]
@rjuju 
Hi Julien, how to enable collector so that I can view DB sessions running, TOP 5-10 problem Session IDs and details etc.

**Comment by rjuju** [comment]
>
> Hi Julien, how to enable collector so that I can view DB sessions running,
> TOP 5-10 problem Session IDs and details etc.
>
did you face any problem when installing it? or are you using the local
mode rather than the remote mode?

>

**Comment by abgarg2022** [comment]
> Hi Julien, how to enable collector so that I can view DB sessions running, TOP 5-10 problem Session IDs and details etc.
> did you face any problem when installing it? or are you using the local mode rather than the remote mode?
> […](#)

No problem in installation, but need to fix below issues I guess before getting DB Stats?
![image](https://user-images.githubusercontent.com/114390414/194808455-ac0a7f9b-70e7-4ef6-ac07-e1289db41d13.png)

**Comment by rjuju** [comment]
I still don't know if you use the remote mode or local mode (see https://powa.readthedocs.io/en/latest/remote_setup.html).

**Comment by abgarg2022** [comment]
> I still don't know if you use the remote mode or local mode (see https://powa.readthedocs.io/en/latest/remote_setup.html).

Since all extensions have been enabled on same Database, so I am using local mode only to gather powa stats.

![image](https://user-images.githubusercontent.com/114390414/194817533-f83263c7-1e2d-4752-8d5f-0bab32917cc5.png)


![image](https://user-images.githubusercontent.com/114390414/194817638-76f57a43-1484-447d-a797-020df0e40b40.png)

**Comment by rjuju** [comment]
If you use the local mode you must use the background worker approach (modifying shared_preload_libraries and restarting as documented for instance at https://powa.readthedocs.io/en/latest/quickstart.html).  The powa-collector shouldn't be used.

**Comment by abgarg2022** [comment]
@rjuju 

I have stopped powa collector now as per below.

![image](https://user-images.githubusercontent.com/114390414/194828068-cc5d0f85-7947-4deb-9d48-70e4ae353c86.png)

Metrics still not available
![image](https://user-images.githubusercontent.com/114390414/194828310-d376834e-3008-4108-b319-f6ecb3657e00.png)

![image](https://user-images.githubusercontent.com/114390414/194828362-df4f0cae-a234-4756-ae0c-d360b1097c7f.png)

**Comment by rjuju** [comment]
Graphs are only available after 2 snapshots (you need at least 2 points to draw a line), so maybe you didn't wait long enoug?

Otherwise, maybe you didn't configure properly the extension in shared_preload_libraries.

**Comment by abgarg2022** [comment]
> 

Below are extensions configured

![image](https://user-images.githubusercontent.com/114390414/194844500-7d3da065-88c7-4fb2-9440-5a363f266943.png)

By when will I be able to see the Session details?

**Comment by rjuju** [comment]
Have you restarted postgres after configuring shared_preload_libraries?  This query should show you what is currently used:

```sql
SHOW shared_preload_libraries
```

How did you configure the powa bgowrker?  This query will show it (assuming it has been restarted)

```sql
SELECT name, current_setting(name) FROM pg_settings WHERE name LIKE 'powa%';
```

Is there any errors in the postgres logs?

**Comment by abgarg2022** [comment]
Below is the output. Let me know in case any log file output needs to be checked?

![image](https://user-images.githubusercontent.com/114390414/194864819-c8016fc8-754a-4d23-9e88-65e2294c0e74.png)

**Comment by rjuju** [comment]
Can you confirm that the extensions mentioned at https://github.com/powa-team/powa-web/issues/161#issuecomment-1273092248 are installed in the powa database, not any other one?

> Let me know in case any log file output needs to be checked?

Yes, please check for any problem in the postgres logs.

**Comment by abgarg2022** [comment]
Seems to be working now, Thanks a lot.

![image](https://user-images.githubusercontent.com/114390414/194901832-31cfcfc5-88b0-4c74-bf2e-4812248453c4.png)

**Comment by rjuju** [comment]
Great!  I'm closing  this issue. Feel free to reopen it or open a new one if you face other problems.
