### ISSUE TITLE
JavaScript errors on the login page

### ISSUE THREAD

**Issue by sajiljosephs** [powa-team/powa-web#171]
![image](https://user-images.githubusercontent.com/87175483/236414233-e4f7d456-d4a5-43ee-bf61-d334e434ae19.png)

There are JavaScript errors on the login page. Can you check on it ?

**Comment by rjuju** [comment]
This is harmless, the error happens because the component doesn't exist on that page.  Once you're login the error won't happen again.

This should be fixed in the upcoming v5, where the frontend part will be entirely rewritten.

**Comment by sajiljosephs** [comment]
Thanks.
