### ISSUE TITLE
Incorrect units of measurement on the time scale on the chart

### ISSUE THREAD

**Issue by plvnv** [powa-team/powa-web#174]
Total runtime = 76s 188ms
Number of Execution = 488910

Total runtime/Number of Execution = 0,00015583 s = 156 µs

But on the chart we see 15 s

powa-web version 4.1.4

![image](https://github.com/powa-team/powa-web/assets/52536610/571b1343-b27c-48d2-901c-51350c13c954)

**Comment by rjuju** [comment]
Hi,

I think it's just a limitation of the current graph framework.  The green series is the number of row, so something between 10k and 15k.  The rest of the series are duration series, but none of them are getting even close to the 15s.  It's just that the underlying library synchronizes both Y axis even if the values are in totally disjoint ranges.  Do you see an value close to 15s when you hover the various series?

You can also try to disable the "#Rows" series only by clicking on the tick (the ✔) next to that series, the Y axis should then automatically scale to the range of the enabled series.  Does it show something closer to the expected duration?

**Comment by plvnv** [comment]
Yes, you seem to be right.

![image](https://github.com/powa-team/powa-web/assets/52536610/e5f9e210-5cee-4623-8812-c411b94cb09f)

**Comment by rjuju** [comment]
Great, thanks for the confirmation!
