### ISSUE TITLE
Error in table: powa_statements_src_tmp

### ISSUE THREAD

**Issue by feddeMurua** [powa-team/powa-web#188]
Hi !

Can you tell me why powa shows me this error? o where I can find the complete log to analyze?? 

Thanks you very much!

<img width="1307" alt="cap1" src="https://github.com/powa-team/powa-web/assets/9412866/2be8d41a-f84d-456a-84b5-5d13daddeb5f">

Best regards,

**Comment by rjuju** [comment]
Hi,

I think the issue is caused by having a different major powa version (X.Y) on the remote server and the repository server.  There's already a patch in the dev version of powa-collector to explicitly check for that and raise an proper error message, it will be release soon.

**Comment by feddeMurua** [comment]
Hi Julien,
Yes, you are right, in one server I have centos with postgres 15, same all
extensions and in the other hand I have postgres 14 including powa.
What should I do? Can I downgrade only powa version ? Or I must equals all
packages (postgres and extensions) from 14 to 15?

Thanks.


*Lic. Murua Federico Nicolás*
*RW - Chubut*

**Comment by rjuju** [comment]
Having different *postgres* versions is not a problem at all, the powa extension takes care of it.  What you can't do is have *powa* in different major versions, but that's usually not a problem to upgrade it on all servers.

Maybe you have powa 4.1.x on one side and powa 4.2.x on the other side?

**Comment by feddeMurua** [comment]
Yes,
that was the problem.
Thanks you very much !
