### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by rjuju** [powa-team/powa-web#199]
@pgiraud 

With the v5 beta approaching, we probably need to formalize the work needed for each new release.  I think it will now be required to run `npm run build`, is there anything else that needs to be done apart the normal tag / GH release and pypi uploading?

Would it be worth creating a RELEASE.md or something like that?

**Comment by pgiraud** [comment]
I was about to create a new `RELEASE.md`but there's actually something mentioned in `CONTRIBUTING.md`. Should we add a specific section for the release process to this document?

**Comment by rjuju** [comment]
I think a dedicated **RELEASE.md** would be better, in that it's less likely that I (or anyone taking care of the release) miss it.

**Comment by rjuju** [comment]
Fixed by https://github.com/powa-team/powa-web/pull/200
