### ISSUE TITLE
Date/hour reset at every page change

### ISSUE THREAD

**Issue by gleu** [powa-team/powa-web#29]
When I set up the time period, data are updated accordingly. That's good. If I click to get to another page (for example, if I click on a database), the time period widget is reset to its default value (last hour). I set it up again. If I click on a query to get more details, the time period is once again reset to its default value.

Not a big issue but this is driving me nuts. And my customer too ;-)

**Comment by rjuju** [comment]
I just tried on a local version, and it seems to work.  Do you have the "?from=..." in the url and/or the links ?

**Comment by gleu** [comment]
Don't know. It was on my customer's computer, and I'm not there anymore. I know it also happened to me previously on my laptop. I'll reinstall powa on a VM to try to reproduce the bug.

**Comment by rjuju** [comment]
After some digging, this has been in powa-web 3.1.1, in c4391f03e219cb3adfed897c736a3416f52bc09a, and 587cc7393d22fc17adb678cce50c7c2a4c91fa66.

**Comment by pgiraud** [comment]
In my opinion, this issue should be closed.

**Comment by rjuju** [comment]
Indeed!
