### ISSUE TITLE
Range picker enhancement

### ISSUE THREAD

**Issue by pgiraud** [powa-team/powa-web#58]
In my opinion, the date range picker could be improved.

I like the grafana's one very much and think we could use some of its features
 - quick ranges (more than we already have),
 - easy to read ranges (`last 3 hours` instead of 2 difficult to read dates),
 - "now-aware" ranges + relative values (ex: now-3h),
 - auto-refresh (is it relevant to have the chart and grid data to be refreshed automatically in PoWA?)

![capture du 2018-06-18 11-37-51](https://user-images.githubusercontent.com/319774/41529073-3ae7c7b8-72ec-11e8-96a2-320c8bc1d4bf.png)

What is others opinion?

**Comment by frost242** [comment]
Seems pretty good to me, far better than what we have now.

**Comment by rjuju** [comment]
I'm all for improving our date range picker.

I'd prefer an "append new values" instead of auto-refresh feature.  However, I'm not sure it'd be that useful compared to the complexity of development, given that on standard installation the powa.frequency should be at least some minutes.

**Comment by rjuju** [comment]
I'm moving this in a bigger issue for various improvements, with a link to this issue.
