### ISSUE TITLE
Web tools

### ISSUE THREAD

**Issue by kavurianil1** [powa-team/powa-web#59]
cat we have web inter face auto timing  every min auto refresh

**Comment by rjuju** [comment]
I'll look into it.  The ideal solution would be to poll for new metrics, but it'll be quite complicated to do.  In the mean time, would an option to activate in the interface that refresh all datasources every minutes if the current interval is not a specific range (last hour, last day and so on would trigger the auto refresh) be ok for you?

**Comment by kavurianil1** [comment]
Hi,

thanks for your update , it will be good

Regards,

Anil

**Comment by rjuju** [comment]
I'm moving this in a bigger wish list for the UI, to ease improvement tracking .
