### ISSUE TITLE
block at starting powa-web

### ISSUE THREAD

**Issue by MBourgetMauger** [powa-team/powa-web#60]
Hello,

i'm tring to start powa-web, i didn't have any error before : 

root@a08sql004:/home/powaweb/powa-web-3.1.3# ./powa-web
[I 180926 10:16:04 powa-web:12] Starting powa-web on http://0.0.0.0:8888

after some time, i did CTRL+C to stop it and get those logs : 

Traceback (most recent call last):
  File "./powa-web", line 13, in <module>
    tornado.ioloop.IOLoop.instance().start()
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 862, in start
    event_pairs = self._impl.poll(poll_timeout)
KeyboardInterrupt

Do you know where i can find more logs ? Or any ideas on those errors ? 

Thanks.
Maxime Bourget-Mauger.

**Comment by ChristophBerg** [comment]
That's not an error, that just means you pressed ^C.
