### ISSUE TITLE
Block at Start 

### ISSUE THREAD

**Issue by MBourgetMauger** [powa-team/powa-web#61]
Hi,

i wasn't enough clear for my last issues, when i try to start powa-web, it stay **stuck.** 
I can't find any log except when i stop it with CTRL+C i get : 

  File "./powa-web", line 13, in <module>
    tornado.ioloop.IOLoop.instance().start()
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 862, in start
    event_pairs = self._impl.poll(poll_timeout)

i guess it get stuck at :   File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 862, in start
but i wasn't able to find more informations even by adding --logging options.

So, my questions are: 
Where can i find logs with informations about that ? 
Does someone have already got this issues and have a resolution ?

Sorry if it seems simple.
Thanks.

**Comment by rjuju** [comment]
Hi,

powa-web is the daemon providing the UI.  It's not stuck (at least it shouldn't be), it just says that the UI is available:

```
[I 180926 10:16:04 powa-web:12] Starting powa-web on http://0.0.0.0:8888
```

and then nothing problematic happened.  powa-web does not run in debug mode, so you shouldn't get much output except errors I think.  Can you try to open the URL the script mentioned in your browser, the application should be available.  If you prefer, you can use http://127.0.0.1:8888, but 0.0.0.0:8888 should work as good.

**Comment by MBourgetMauger** [comment]
Thanks for your feedback, i can't access to it now, but i will look to my network configuration.
