### ISSUE TITLE
Wrong last release reference ?

### ISSUE THREAD

**Issue by julmon** [powa-team/powa-web#64]
Hello,

It seems github `last release` link (https://github.com/powa-team/powa-web/releases/latest) is pointing to 3.1.4. I wonder why it's not 3.2.0.

Thanks,

**Comment by rjuju** [comment]
Indeed it's required to manually create a release after a tag is pushed, that makes sense.

Thanks for the report, it's now fixed.

**Comment by julmon** [comment]
Thanks !

I guess you're going to fix it on powa-archivist repository too.

**Comment by rjuju** [comment]
Yes, I just checked all other repo I'm maintaining and this was the only one lacking.  pg_qualstats also needs to be uploaded on pgxn, I will ask @rdunklau.
