### ISSUE TITLE
Showing explain with/without index when no indexes are suitable

### ISSUE THREAD

**Issue by gleu** [powa-team/powa-web#69]
It looks like PoWA shows the explain plan with and without index even when no indexes are suitable according to it. Doesn't sound consistent to me :)

**Comment by rjuju** [comment]
Agreed!  Thanks a lot, I'll fix soon.

**Comment by rjuju** [comment]
Fixed in 9a137ebe10f5d06047855dcaf6afb5d21928c96b.

**Comment by gleu** [comment]
Thanks!
