### ISSUE TITLE
Installing powa-web on Windows

### ISSUE THREAD

**Issue by ErwanVideo** [powa-team/powa-web#72]
Hello, I would like to install powa-web on Windows but I have some issues doing so. I installed python, psycopg2, sqlalchemy and tornado using pip. When I try to run the "run_powa.py" file with PyCharm I get this text : 

> C:\Users\erwan.beta\AppData\Local\Programs\Python\Python37-32\python.exe C:/Users/erwan.beta/Downloads/powa-web-master/run_powa.py
> You should define a server and cookie_secret in your configuration file.
> Place and adapt the following content in one of those locations:
> 
> 	/etc/powa-web.conf
> 	C:\Users\erwan.beta/.config/powa-web.conf
> 	C:\Users\erwan.beta/.powa-web.conf
> 	./powa-web.conf
> 
> servers={
>   'main': {
>     'host': 'localhost',
>     'port': '5432',
>     'database': 'powa'
>   }
> }
> cookie_secret="SUPERSECRET_THAT_YOU_SHOULD_CHANGE"

But because I am on Windows I don't really understand where I should create the powa-web.conf file, do you know where I should create it ?

I am not really sur if it's clear, thank you in advance for your time.

**Comment by rjuju** [comment]
Hello,

I don't have a windows to test on, but according to the error you can create the file in either

* C:\Users\erwan.beta/.config/powa-web.conf
* C:\Users\erwan.beta/.powa-web.conf
* same directory as where run_powa.py is located

Also, be careful that run_powa.py starts powa with debug enabled.  You should consider using powa-web.py instead.

**Comment by ErwanVideo** [comment]
Ok I'll try this and keep you updated. 

Thank you !

**Comment by ErwanVideo** [comment]
What you told me worked. I created the configuration file in the same directory as where 'run_powa.py' is and the error disappeared. Thank you very much ! 

However I still had some small issue with the server so I think I won't use it with Windows.
