### ISSUE TITLE
Add of a button to run a script on the server 

### ISSUE THREAD

**Issue by ErwanVideo** [powa-team/powa-web#74]
Hello, 
First of all, thank you very much for Powa ! It is great tool and it is very nice of you to make it available for all of us !

I just have a question. I wanted to add a button which when clicked upon, would run a script which is in the server (at the same place where powa-web is installed). I tried to use a link this way and a form the same way : 
`<a href="{{ static_url('script/test.sh') }}">test</a>`

`<form action="{{ static_url('script/test.sh') }}"   methode="POST">
        <button type="submit"  class="launcher button radius" style="margin-left: 5%;"> TEST </button>
     </form>`

But both of them just make me download the script but they don't run it. 
I also tried to use ajax but I didn't have any luck wih it...

I was wondering if you had any idea of how  to do it ? 

PS : I wrote this code in the "layout.html" page.

**Comment by rjuju** [comment]
Hi.

Thank you very much!

About your need, the biggest problem here is that it would be a huge security breach, so we unfortunately can't implement that.  You can find a lot of better adapted tools for that.
