### ISSUE TITLE
TimeView graph is not synchronized with GraphView

### ISSUE THREAD

**Issue by pgiraud** [powa-team/powa-web#86]
The behavior of the preview (below the graph) is very messy. It's quickly desynchronized with the corresponding chart and is sometimes displaying incorrect highlight information.

In the example below, I decided to display data for the 14th of august in the demo.
https://dev-powa.anayrat.info/server/0/overview/?from=2019-08-14T00%3A00%3A00%2B02%3A00&to=2019-08-14T23%3A59%3A00%2B02%3A00

Then I decided to use the date picker and switched to last hour range.

At that point, the preview still shows data for the 14th.

![Capture du 2019-08-16 10-59-39](https://user-images.githubusercontent.com/319774/63156570-3d7d9f80-c015-11e9-97ee-133f602c9d84.png)

Going further, I zoomed in the main chart using the mouse. The preview data still haven't changed. A section is highlighted though.

![Capture du 2019-08-16 11-04-17](https://user-images.githubusercontent.com/319774/63156732-9e0cdc80-c015-11e9-813c-18afb78f2353.png)

**Comment by rjuju** [comment]
I'm closing this issue since you fixed it in the upcoming v5, when doing a total rewrite of the frontend.
