### ISSUE TITLE
FETCH FORWARD 4096 IN 

### ISSUE THREAD

**Issue by Paulpatou** [powa-team/powa-web#91]
Hello, I don't know if I'm asking my question in the right place but in powa-web I have this request that appears often and I don't understand what it corresponds to. If you have an idea?

![image](https://user-images.githubusercontent.com/33478981/70318839-3e834880-1821-11ea-9b74-5c4d90c043ef.png)

![image](https://user-images.githubusercontent.com/33478981/70319193-fdd7ff00-1821-11ea-8070-957343529dea.png)

**Comment by rjuju** [comment]
Hello,

This is probably an artifact of a library you're using, most likely in python, that behind the hood use cursors and fetch records with a 4096 batch size.

Unfortunately pg_stat_statements doesn't normalize utility statements.  You probably have with a lot of similar entries, which isn't terribly helpful.  I'm wondering if we shouldn't try to manually normalize such statements in powa, to gather some or all variants of FETCH (and maybe others commands) together.  Normalizing at least the cursor name should already help in many cases without removing important information.
